GSoC-interest.md
Hey everyone, I am Pranjal Aswani ([aswanipranjal](https://github.com/aswanipranjal)) and I am interested in the project: Reporting of CHAOSS Metrics. 
This pull request adds my details to the list of interested students.
Looking forward to working with you guys!
=> add information about @aswanipranjal

GSoC-interest.md
Hey, I've added the link to my proposal draft. If you can kindly review it once?
=> Added proposal link for Pranjal Aswani

GSoC-interest.md
=> Updated GSoC-interest.md

CHAOSScon/2018-chaosscon-na.md
Hi everyone,
This is a first pass at a CFP for CHAOSScon NA 2018.
The core of it is copied from the LF OSS NA CFP. I already adjusted it a little bit. Feel free to make comments and suggest specific changes. 
I suggest, we use this pull-request for all CFP related conversation, until it is ready and we merge it.
=> Start on CFP for CHAOSScon NA 2018

CHAOSScon/2018-chaosscon-na.md
The day of week for a couple of the dates didn't match the actual dates, so I changed the day of the week to match the corresponding date.
=> Fixed dates

GSoC-Ideas.md
This is a proposal for GSoC'2019.
=> Idea for GSoC: Support of Source Code Related Metrics

GSoC-Ideas.md
I've added the link to the corresponding issue. I created the issue in GrimoireLab project as the idea is related to it, but I can move it to another project if you think it would be more appropriate.
=> Add link to Idea 1 micro-tasks

GSoC-Ideas.md
Pranjal, who was a GSoC student with us in 2018, showed interest in helping to mentor this year.
Both Valerio and me agree that he could be a good mentor in the ideas that we´re proposing,
since he is familiar with the technology, and has the experience of being a GSoC student.
So, I'm adding him to our ideas, as a mentor.
=> [GSoC] Add Pranjal Aswani to some of the ideas, as a mentor

GSoC-Ideas.md
Was going through the ideas and noticed a link that led to nowhere. I found this sample code link which seemed to be the intended one. Please have a look
=> update broken link to sample project

GSoC-interest.md
fix #86 by requesting microtasks in public repos. We do not accept plagiarism.
=> Add GSoC expectation to reference other's works

project-charter.md
- add Working Groups
- change "Technical Committee" to "Committee"
- remove language from when we started
replaces part of #71
=> Update Charter: update project structure and add working groups

GSoC-interest.md
Signed-off-by: Parth Sharma <parth261297@gmail.com>
=> Added my name & details to GSoC-Interest

GSoC-interest.md
Signed-off-by: Apoorva Anand <apoorvaanand.work@gmail.com>
=> Add apoorvaanand1998 to GSoC-interest

GSoC-interest.md
HI 
I have complete microtask 0 and completing rest of it.
I will be adding a link to the proposal soon.
Please Review looking forward to get feedback
=> Add @sarvesh211999 as GSoC interested student

GSoC-interest.md
Signed-off-by: Aniruddha Karajgi <akarajgi0@gmail.com>
=> Add gsoc information for Aniruddha Karajgi (Polaris000)

GSoC-Ideas.md
This pull request puts the Augur idea up top in the hopes to balance interest from GSoC applicants. 
This change was proposed by Matt on the weekly hangout 2019-03-26 and agreed to by Sean and Jesus.
=> change order of ideas

GSoC-interest.md
I opened this PR. I will be completing the proposal soon.
Thanks. :slightly_smiling_face:
=> add information about @vchrombie

GSoC-interest.md
Signed-off-by: Jose Alberto <quirroone@gmail.com>
=> add information about @quirroone

GSoC-interest.md
Signed-off-by: Neha Saini <nsaini.cse20@gmail.com>
=> Add details for GSoC idea: Visualization of metrics in kibana

GSoC-interest.md
Creating a new PR because rebasing with master was creating conflicts and I did not know how to solve them so forked the repo again and created PR reflecting changes from add-info branch. 
Signed-off-by: InosRahul <rahulsoni2225@gmail.com>
=> Add information about @InosRahul as GSoc Interested student

GSoC-interest.md
Signed-off-by: Bingwen Ma <root@bing0ne.com>
=> Add information about @bing0n3 as GSOC interested student

GSoC-interest.md
I am very interested in the ideal 3 and have completed all the microtasks. I added my information and proposal to this list. To resolve the conflict, I have closed my previous pr.
Signed-off-by: Xin Tan <746534561@qq.com>
=> Add information about @SunflowerPKU as GSoC Interested student

CONTRIBUTING.md
Signed-off-by: Georg J.P. Link <linkgeorg@gmail.com>
=> fix link to DCO browser plugin

social-media-README.md
Signed-off-by: Georg J.P. Link <linkgeorg@gmail.com>
=> fix formatting on social media readme

community-handbook/README.md
This pull request will make it easier to find the coordinating issue from the Handbook.
=> add link to #105 in Community Handbook

community-handbook/handbook-usage.md
This pull request adds spaces to fix the indentation level of bullet points
=> fix list indentation

GSoC-interest.md
Signed-off-by: Matt Germonprez <germonprez@gmail.com>
Updates to the Interest Page for 2020
=> Update GSoC-interest.md for 2020

GSoC-Ideas.md
This commit proposes 3 ideas that target the grimoirelab platform.
The micro-tasks will be available soon.
=> [gsoc-ideas-2020] Grimoirelab

GSoC-Ideas.md
I would like to participate as a mentor for CHAOSS during GSoC'20 for some grimoirelab projects. I have added myself as a mentor for these. @valeriocos @GeorgLink please have a look.
Thanks
=> Adding Polaris000 as mentor for some project ideas

GSoC-Ideas.md
This PR is adding the GSoC idea about implementing the SCMS with GrimoireLab.
=> Add idea for SCMS

GSoC-Ideas.md
Signed-off-by: Matt Snell <msnell@unomaha.edu>
=> Update D&I Badging link to new location

community-handbook/README.md, community-handbook/metrics-release.md
This PR proposes to add the CHAOSS Metrics Release process to the Community Handbook.
=> Describe Metrics Release process

Outreachy-ideas.md
Signed-off-by: Matt Snell <msnell@unomaha.edu>
=> Update Link for D&I Badging Idea

Outreachy-interest.md
Added my personal and project info and signed off properly now.
=> Added personal and project info to Outreachy-interest.md

Outreachy-interest.md
Signed-off-by: thecraftman <temitopetola@gmail.com>
=> Added Outreachy proposal, microtasks & links

Outreachy-interest.md
Signed-off-by: Perez Ogayo <pogayo17@alustudent.com>
Completed the Microtasks for _Build Workflow Process for CHAOSS Diversity & Inclusion Badging  Project_ .
=> added project and personal info to Outreachy_interest.md

community-handbook/README.md, community-handbook/chaosscast.md
=> add CHAOSScast to Handbook

community-handbook/README.md
Signed-off-by: Mariam Guizani mariam.guizani@gmail.com
=> Fixed typo in the readme

GSoD-ideas.md, GSoD-interest.md
This PR creates the files and adds the relevant information and guidelines for GSoD 2020.
@GeorgLink, I created the files and add some basic information. Feel free to add/suggest more changes.
/cc @germonprez
=> [GSoD] Create GSoD-ideas.md and GSoD-interest.md

GSoD-interest.md
Signed-off-by: tharun143 <tharunravuri2000@gmail.com>
=> Adding my proposal link

community-handbook/chaosscast.md
=> Add coordinator functionality, streamline scheduling process

GSoD-interest.md
Signed-off-by: Jaskirat Singh <juskirat2000@gmail.com>
=> Added my GSoD Proposal

community-handbook/chaosscast.md
Hi @ElizabethN, 
This PR fixes the roles for the episode planning steps.
=> fix roles for planning a CHAOSScast episode

GSoD-interest.md
Signed-off-by: kritisingh1 <kritisingh1.ks@gmail.com>
Adds work proposal for Google Summer of Docs 2020
=> Add GSoD proposal - GrimoireLab Tutorial

GSoD-interest.md
Signed-off-by: JackieBinya <jacquelinebinya@gmail.com>
=> Jacqueline Binya GSOD-2020 Application

community-handbook/chaosscast.md
=> Add action item: one week reminder email

GSoD-interest.md
Signed-off-by: Xiaoya Xia <xiaoyaxiaesther@gmail.com>
=> Add my GSoD proposal

community-handbook/chaosscast.md
@GeorgLink if you do not want to publicly include the zoom link for recording with rebase.fm that's totally fine! I just didn't want it to get lost somewhere. :smile:
=> Add Armstrong, Update Rebase.fm process

community-handbook/metrics-release.md
These are the steps I completed today to create the Release 2020-08 PDF
=> add process for creating Metrics Release PDF

community-handbook/README.md, community-handbook/chaosscast.md, community-handbook/chaosscon.md, community-handbook/community-report.md, community-handbook/handbook-usage.md, community-handbook/metrics-release.md, community-handbook/metrics-translations.md, community-handbook/roles-responsibilities.md, community-handbook/website.md
We now have the handbook in GitBook
=> Add move handbook notice

GSoC-Ideas.md, README.md
Fixed two typos in docs. There was actually no description about which branch to send PR on so I'm sending this directly to master. If I need to send the PR to some other branch and not directly on master please let me know. 
Signed-off-by: Amanjot Singh <theamanjs@gmail.com>
=> fixed typos in readme and gsoc-ideas file

GSoC-Ideas.md
Signed-off-by: Kevin Lumbard <kmlumbard@gmail.com>
This pull request removes the automated community report idea. At this time, the idea does not seem feasible. Discussion included @germonprez and @vinodkahuja 
This pull request also adds the issue link for the website navigation prototype idea and new mentor.
=> GSoC website idea edits

GSoC-Ideas.md
Signed-off-by: Kevin Lumbard <kmlumbard@gmail.com>
=> update website GSOC ideas

GSoC-interest.md
=> Update Title to 2021

GSoC-interest.md
Signed-off-by: Sourabh Saraswat <saraswatsourabh5@gmail.com>
=> Updated Older Micro-task Link to GSOC'21 idea list link .

GSoD-ideas.md
This commit updates the GSoD ideas page with the latest ideas.
@GeorgLink @sduenas @sgoggins @klumb
=> [gsod-2021] Update GSoD-ideas.md

CONTRIBUTING.md
I rephrased some words and added some extra information about contributing to CHAOSS. 
My opinion: I think some headers should be of smaller sizes to conform to visual hierarchy. I was also thinking of making the file a little friendly by adding emojis.
Do you think pictures should be added to help explain some points?
I would love to know if the changes I made are good to go so I can continue making changes.
Thank you
=> Making changes to Contributing.MD

GSoC-interest.md
Signed-off-by: Pankaj Biradar <pankaj28988@gmail.com>
=> Added GSoC proposal - Pankaj Biradar

CONTRIBUTING.md
Added extra description for beginner contributors. Also fixed some typos. I was thinking of making the tone of the docs more friendly.
=> Add extra description for beginner contributors

GSoD-interest.md
This commit updates the GSoD Interest page for the year 2021.
=> Update GSoD-interest.md for 2021

GSoC-interest.md
Signed-off-by: Rashmi K A <k.a.rashmi04@gmail.com>
=> Add GSoC proposal - Rashmi K A

GSoC-interest.md
Add a GSoC proposal of BoxuanZhao
=> Add a GSoC proposal - Boxuan Zhao

GSoC-interest.md
Signed-off-by: Steven Kolawole <45284829+SteveKola@users.noreply.github.com>
=> Add microtasks and proposals

templates/CONTRIBUTING.md, templates/WG-README.md, templates/code-of-conduct.md
Hi everyone,
As discussed in #277, I have created some templates that can serve as a guide on standardizing the files.
The templates are for the following files:
- README.md
- CONTRIBUTING.md
- code-of-conduct.md
Signed-off-by: Yash Prakash <yash2002109@gmail.com>
=> Add templates for standardization of files in each WG

CONTRIBUTING.md
- Added guide for using DCO GitHub UI. 
- Added a that explains how to write good commit messages.
- Fixed some typos.
- Changed the PR checklist
=> Added guide for using DCO GitHub UI

Summer-OSPP-ideas.md, Summer-OSPP-interest.md
This PR would create the required pages for organizing the participation in Summer 2021 of the Open Source Promotion Plan.
Related to #275 
@GeorgLink @xiaoya-Esther, it would be great if you can review the PR.
=> Create ideas and interest pages for Summer-OSPP

Summer-OSPP-interest.md
Signed-off-by: sevagenv <sevagenv@gmail.com>
=> [Summer OSPP] Add proposal

GSoC-Ideas-2021.md, GSoC-Ideas.md, GSoC-interest.md
Waiting for the organization submission site to open up to validate completeness. Dates are correct. Ideas template is set out empty and validated, with a link to a separate archive of our 2021 ideas for people to reference.
=> Preliminary GSOC 2022 Updated Guidelines

GSoC-Ideas.md
=> Add badging-bot GSoC Idea

GSoC-Ideas.md
Signed-off-by: amino19 <anshumaankrprasad76@gmail.com>
----------
Hey there, :wave: 
Things I changed via pull request are as follows:-
- Indentation in the document
- A link has been broken, corrected now!
- `site` => `GSoC site`
I hope you consider these changes!
Thanks! :sparkles:
=> ✨ | Enhancing GSoC-Ideas Documentation

GSoC-Ideas.md
Signed-off-by: Ramya Kappagantu <ramyasanjana1999@gmail.com>
=> Updated GSoC-Ideas.md with the correct links

GSoC-Ideas.md
Signed-off-by: Ramya Kappagantu <ramyasanjana1999@gmail.com>
=> Updated GSoC-Ideas.md with the correct augur workers link

GSoC-interest.md
Signed-off-by: Siddhi Gupta <siddhiiguptaa@gmail.com>
=> Added entry to GSOC

GSoC-interest.md
Signed-off-by: kaxada <ekaxada@gmail.com>
=> added name and projects' links

GSoD-interest.md
Signed-off-by: Muhammad Rafly Andrianza <luphieanza@gmail.com>
=> Add Muhammad Rafly Andrianza GSoD Proposal

GSoD-interest.md
added myself for the Google Season of docs
=> added myself for google season of docs

GSoD-interest.md
Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>
=> Add Xiaoya's Proposal to GSoD-interest.md

GSoD-interest.md
I added my interest information to the table.
=> Add Ruth interest info in GSOD

docs/community-initiatives/chaosscon.md
cc @Ruth-ikegah @xiaoya-yaya Merge whenever you like.
=> Adds a few quick changes

docs/community-initiatives/chaosscast.md
@Ruth-ikegah @xiaoya-yaya I think these changes bring this document up to speed. I will let you merge in whenever you're ready.
=> Updates process changes

docs/community-initiatives/chaoss-meetings.md
This updates the process for publishing meetings. Procedure before meetings might be replaced with the [Facilitation Guide](https://docs.google.com/document/d/1fCxgKXmvASZ2OQA3Eu9OqlzuFSdPtNZHInJHYr0vF8g/edit)? It's really up to you all. :blush:
=> Updates publishing section

working-groups/README.md, working-groups/wg-repository-structure.md
Signed-off-by: GitHub <noreply@github.com>
=> add working group folder

local-communities/chaoss-africa/info.md, local-communities/chaoss-asia/info.md
Signed-off-by: Ruth Ikegah <ruthikegah@gmail.com>
=> add local communities

governance/path-to-leadership.md, governance/roles-and-responsibilities.md
=> Review path-to-leadership and roles-and-responsibility

docs/community-initiatives/chaoss-meetings.md
=> Adds a step to clarify

README.md, governance-in-chaoss/board-of-directors.md, governance-in-chaoss/path-to-leadership.md
=> Update governance-in-chaoss section

how-work-is-done/community-projects/dei-badging/event-badging/the-badging-bot.md
Signed-off-by: kaxada <ekaxada@gmail.com>
=> added missing bot info

our-local-chapters/chaoss-asia.md
=> Add CHAOSS Asia chapter

how-to-contribute/mentorship/mentorship-best-practice.md
=> Update mentorship best practice document

chaoss-media-outreach/newsletter.md
=> Draft newsletter page

README.md
=> Add Ruth and Xiaoya as maintainers

chaoss-media-outreach/brand-style-guide.md
=> Add brand-style-guide.md

mentorship-programs/2022/GSoD Final Case Study.md
This is the document we need to submit in conjunction with our Final Evaluation for the GSoD 2022 program. 
=> Create GSoD Final Case Study.md

how-to-contribute/quickstart-for-newcomers.md
=> fixes formatting bug

chaoss-media-outreach/chaoss-meetings.md, how-to-contribute/design-contribution.md
=> Fix some broken links

how-to-contribute/design-contribution.md
=> testing link to images

local-chapters/chaoss-asia.md
Edited the word "locolized" to "localized", "who" to "whom", added @xiaoya-yaya Github link on her name, and changed the meeting time as suggested by @ElizabethN and @Ruth-ikegah.
Thanks!
Signed-off-by: Shreyansh Keshav <shreykeshav33@gmail.com>
=> Updated chaoss-asia.md

how-to-contribute/quickstart-for-newcomers.md
Today in the DEI working group we decided to add this prompt to the first three things for newcomers.
=> Add prompt to type newbie in slack

how-to-contribute/DCOsetup.md
=> Adds more info, fix formatting

how-to-contribute/quickstart-for-newcomers.md
=> Add link to Discourse

how-to-contribute/teams-at-chaoss.md
=> updates contacts and team info

how-to-contribute/quickstart-for-newcomers.md
=> Add link to next step - participating

how-to-contribute/teams-at-chaoss.md
=> Updates OSPO WG and Contact

how-to-contribute/README.md, how-to-contribute/community-guidelines.md, how-to-contribute/content-contribution.md, how-to-contribute/development-contribution.md, how-to-contribute/documentation-contribution.md, how-to-contribute/metrics-contribution.md, how-to-contribute/open_source_intro.md, how-to-contribute/teams-at-chaoss.md
Adding a disclaimer to how to contribute section for deleting unnecessary files that are no longer needed. 
Refer PR https://github.com/chaoss/community/pull/539
Signed-off-by: Vinod K. Ahuja <vahuja@unomaha.edu>
=> Adding disclaimer

.github/ISSUE_TEMPLATE/02-chaosscast-episode-checklist.md
update issue template with correct link to where the episode images can be found
=> Correct episode image link

.github/ISSUE_TEMPLATE/02-chaosscast-episode-checklist.md
Added a note to include a mention of Sustain who pays for our podcast hosting account
=> Minor update to CHAOSSCast Issue Template

data-use-statement.md
This PR adds the missing links to Data statements in the README, ensuring that contributors worldwide would know how to effectively contribute to the project
Closes #523
=> feat: adding missing links to Data Statements 

chaoss-groups/software-projects.md
This adds a little more information and Slack links where available.
=> Adds Slack links

community-contributions.md
I changed my mind about explicitly describing what counts as a contribution. :smile:
=> Updates community-contributions.md

community-contributions.md
This adds a list of the types of contributions so we may be more granular in our measurement and make sure we aren't missing anything in our Types of Contributions metric.
=> Adds types of contributions

.github/ISSUE_TEMPLATE/02-chaosscast-episode-checklist.md
fixed case in issue template label for chaosscast
=> fixed case in issue template

community-contributions.md
Took notes during the CHAOSS Africa Community call.
=> Took notes during CHAOSS Africa meeting

community-contributions.md
Signed-off-by: AdeyinkaOresanya <adeyinkaoresanya@gmail.com>
=> Update community-contributions.md with Adeyinka's non-code contributions

chaoss-groups/working-groups.md
Updated the names of several WGs that have changed and added the Data Science and UN SDG WGs.
=> Several updates to the WG list on the website

community-templates/metric-template.md
Updated the Metric template to use the New Metrics Template.
- Removed the following sections: 
1. Description
2. Objective
3. Tool proving metric
- Moved the tags to the bottom of the metrics template
- Added the following section:
1. Overview 
2. Want to know more?- as a dropdown that contains the Data Collection Strategies, Filters and Visualization.
=> Update Metric-template.md 

community-templates/Glossary.md
Here is the full Glossary Document for CHAOSS Abbreviations. However @ElizabethN as recommended this file is by alphabetical order.
=> Glossary.md
