Project Charter.md
Text is copied from the Website.
Fixed error in 2.3. removed duplicate "be be"
=> add Project Charter

code-of-conduct.md
**IMPORTANT: Do not merge, until the CHAOSS Governance Board has formally adopted the Code of Conduct for the CHAOSS community.**
The Code of Conduct workgroup is finalizing the text of a Code of Conduct that will be proposed to the CHAOSS community.
The Contributor Covenant has most of our desired features and is the basis of our own Code of Conduct.
We added a paragraph from Geek Feminism about the reporting and consequences. (paragraph starting with "We will respect confidentiality")
We added a paragraph about reporting yearly incidence report numbers and reviewing the CoC. (paragraph starting with "The CHAOSS Governance Board will")
=> Adopt Code of Conduct

Project Charter.md
Rationale: We've been using the name Software Committee for a while (at least in some context), and my feeling is the word "software" is much less ambiguous than "code", thus making it more clear what the TC is for.
Note: According to the charter, this modification needs two thirds of the GB, so this is really a proposal to be discussed in the next GB meeting. Comments to this pull request are welcome in advance to that discussion.
=> Change name of the Code Comittee to Software Comittee

code-of-conduct.md
v1.1
- update email address
- change requirements for Code of Conduct team to be more inclusive
- change to three members of team to have a tie-breaking vote
Motion for Governing Board to vote "accept these changes".
=> Update CoC team requirement and email address

code-of-conduct.md
The Code of Conduct election results are in: https://civs.cs.cornell.edu/cgi-bin/results.pl?id=E_eb0e86af55a181a9
There were no write-ins and the three candidates 
- Nicole Huesman
- Armstrong Foundjem
- Georg Link
are elected to serve on the Code of Conduct Team for two years. The term is 6/8/2018 - 6/7/2020
=> Code of Conduct Team Election Results

CONTRIBUTING.md
After some discussion in the mailing list (see [1] [2] for conclusions, and whole thread [3] [4] for context), I've drafted this proposal which hopefully captures the result of that discussion.
Any feedback is welcome.
[1] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000173.html
[2] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000186.html
[4] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000157.html
[3] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000169.html
=> Proposal for a text on how we make decisions

GSoC-Ideas.md
This is a proposal for GSoC'2019.
=> Idea for GSoC: Implementing CHAOSS metrics with Perceval

GSoC-Ideas.md
=> Augur Submission One

project-charter.md
This pull requests adds a rule that when a Governing Board meeting does not reach 2/3 quorum, a new meeting with the same agenda can be called two weeks later and quorum requirement is dropped to 1/2.
partly replaces # 71
=> Change Charter: add quorum rule to repeat a meeting

project-charter.md
This pull requests links to the code of conduct from the charter. We did not have a code of conduct when we wrote the charter but now we do.
partly replaces #71
=> Update Charter: add link to current code of conduct

community-handbook/README.md
I propose that CHAOSS starts documenting roles and processes in a handbook.
The goal is to have a central place for community members to learn about how CHAOSS operates. 
This should help with onboarding and aligning practices across committees and working groups.
The GitLab handbook served as an inspiration.
https://about.gitlab.com/handbook/
=> Community Handbook proposal

code-of-conduct.md
Signed-off-by: Venu Vardhan Reddy Tekula <venuvardhanreddytekula8@gmail.com>
=> fix minor typos in CoC

GSoC-interest.md
This pull request adds a notice to the GSoC interest page to inform students that they are required to include a DCO signoff.
=> add DCO requirement to GSoC interest page

community-handbook/README.md, community-handbook/handbook-usage.md
In starting off the handbook, it would be great to agree on a structure of the handbook up-front.
This pull request is the first implementation of using a pull request to discuss changes to the handbook.
Please comment on specifics and let's figure out together how we want the CHAOSS Community Handbook to be structured. To start, I copied the GitLab handbook and made some changes. I don't know whether a `function/process` oriented structure will work well for CHAOSS. Maybe we go straight to the processes, since we don't have many different functions. -- Thoughts?
=> Handbook page on how to use and structure the handbook

GSoC-Ideas.md
This PR provides some fixes in the titles and content of the GSoC ideas for GrimoireLab.
=> [gsoc] Minor fixes on GrimoireLab ideas

GSoC-Ideas.md
Signed-off-by: Matt Snell <msnell@unomaha.edu>
This is a start! Let me know what you think!
=> Add D&I Badging to GSoC List

community-handbook/README.md, community-handbook/chaosscon.md
The handbook page for organizing CHAOSScon was initially drafted back in May (https://github.com/chaoss/governance/issues/105#issuecomment-491045895). I made small changes to it, but it would be much easier if we commit it to the handbook and then improve it there.
This PR is to get an initial version added to the handbook.
=> add handbook page for chaosscon

GSoC-Ideas.md
In the past, we changed the order of GSoC ideas occasionally to give every idea an equal chance. I used a randomizer to determine the new order and this PR implements it.
New Order | Old Order | Ideas
-- | -- | --
1 | 6 | Idea: Creating Quality models using GrimoireLab and CHAOSS metrics
2 | 3 | Idea: (Blockchain) : Open Source Health and Sustainability SSO   Implementation with Hyperledger/Indy and OAUTH
3 | 4 | Idea: Boosting data processing in GrimoieLab
4 | 2 | Idea: Implementation of GitLab Data Collection Workers
5 | 8 | Idea: Implement the Social Currency Metrics System in GrimoireLabs
6 | 7 | Idea: Build Workflow Process for CHAOSS Diversity & Inclusion Badging
7 | 1 | Idea: Machine Learning for Anomaly Detection in Open Source Communities
8 | 5 | Idea: Packaging and Sharing …
=> scramble GSoC idea order

community-handbook/README.md, community-handbook/roles-responsibilities.md
We had an [email about Succession Planning on the mailing list](https://lists.linuxfoundation.org/pipermail/chaoss/2020-February/001083.html) and discussed it further on the weekly call 2020-02-25, extending the list of [roles and responsibilities in a google doc](https://docs.google.com/document/d/1UWop73-e8d9m_gv3P5LmB2ybe_eJri-HHiUKGrIuZzc/edit?usp=sharing). 
This PR adds that list to our handbook. It is not intended to be complete and is expected to change over time. Adding it to the handbook gives us something to refer to and to improve.
=> Add Roles and Responsibilities to Handbook

community-handbook/roles-responsibilities.md
Inside CHAOSS, most of the people who perform those tasks are not building software.
=> Changing "software developer" to "Contributor"

GSoC-interest.md
This PR adds my details, microtask repository link and proposal document link in GSoC-interest.md . As of now, my microtask answers are in a Google doc which has been linked in the README of the microtask repository. The Proposal document does not contain any GSoC idea related details yet, but that's where my final proposal will live.
=> Add microtask repository and proposal document link

GSoC-Ideas.md
The GSoC website points only to the ideas. I have the impression that students are not finding the page where we are describing our selection process. This PR adds a link to the critical, important page that GSoC students need to know.
=> point to GSoC-interest.md

Outreachy-ideas.md
I believe Outreachy posts ideas on their website, unlike GSoC. This PR adds a disclaimer and link to Outreachy on the ideas page because I think we did not submit all of the ideas from our markdown file.
=> add disclaimer to Outreachy ideas page

community-handbook/metrics-release.md
Signed-off-by: Kevin Lumbard <kmlumbard@gmail.com>
Added detail to the release process. Not completely sure on all of this so I welcome discussion.
=> update release handbook

community-handbook/chaosscast.md
CodeFund Podcast Network is regrouping as Rebase.fm after CodeFund closed down.
This pull requests updates our documentation accordingly.
=> update CHAOSScast with changes of CPN->Rebase.fm

community-handbook/metrics-release.md
The release process in the Handbook is missing the release candidate page that is central for pointing people to what metrics need reviewing for the release and seeing what the metrics would look like after the release.
This Pull Request details the steps required to release CHAOSS metrics as I understand it from conversations we had.
Please add any steps and details I may have missed.
Please suggest improvements to make it simpler for everyone.
The goal of this PR is to ensure we have a defined process that anyone in the CHAOSS project can follow. There may be details missing on how to execute steps and I'm happy to provide more details.
=> Describe Release Process with changes

community-handbook/chaosscast.md
We have a template for the show notes that is outdated. Specifically, CPN now is Rebase.fm and the sponsor changes.
In conversation with Rebase.fm, they will make sure all information is in the show notes that they prepare for us.
From now on, we can use the show notes as they come, without converting it to our own template.
=> Discontinue using Template for podcast show notes

community-handbook/README.md, community-handbook/community-report.md
This PR is for adding a handbook page for describing the process CHAOSS follows for delivering the Community Report.
=> Add Community Report to Handbook

GSoC-Ideas.md
This PR updates the ideas page with the issue links for the microtasks, discussion related to the idea, and clarifying doubts of the GrimoireLab projects.
@GeorgLink @sduenas
=> [gsoc-2021] Update GSoC-ideas.md with the links

README.md, community-handbook/README.md
Hi,
This PR is to maintain consistency with other repositories,
by removing the `./` notation from READMEs
Signed-off-by: ritik-malik <ritik18406@iiitd.ac.in>
=> removing dot-slash notation

Summer-OSPP-ideas.md
The mentors for the GrimoireLab project idea (Summer OSPP) would be using https://github.com/chaoss/grimoirelab/issues/433 as the means of communication.
@GeorgLink, please review this PR when you have time.
Thanks.
=> Add microtasks and discussion issue link

templates/focus-areas.md
Hi,
As discussed in #276, I added the templates for focus-areas READMEs,
Would be happy to do the suggested changes.
Signed-off-by: ritik-malik <ritik18406@iiitd.ac.in>
=> added focus-areas template

GSoC-interest.md
Signed-off-by: Ayush <ayu08kau@gmail.com>
=> Completed the MicroTasks

GSoD-proposal.md
GrimoireLab is not participating in the GSoD 2022. This PR removes the content related to the previous year application.
It looks like there is a lot of previous year content. Please let me know if I have to update anything within this PR.
=> [GSoD] Remove last year application content

how-to-contribute/quickstart-for-newcomers.md
Based on conversations in the [DEI working group ](https://docs.google.com/document/d/1MzDk84BL7FfHDxbFxJz39M72V2Hfc5Y6oCPhOl6woxo/edit#heading=h.tdkbppxyuyyl) and Community Calls, we decided that we wanted to streamline the Quickstart and identify three steps a newcomer can take to get acquainted with CHAOSS. These are the three we identified:
- Join general Slack
- Join Office Hours
- Join Monthly Onboarding (or watch a recording)
I'd like to move some of the info that was previously in this Quickstart into maybe a new doc called "Next Steps: Participating in CHAOSS" or something like that, as we shift to more of a learning path for our contributor funnel. The next stage would be "Participating," as we [discussed in the DEI working …
=> Streamline Quickstart

community-resources/templates/metric-template.md
As I was developing a new metric, Google docs spell checker pointed out that we were missing an 'e' in delineated, so here's a quick spelling fix.
=> Fixed spelling of delineated in the template

community-initiatives-and-working-groups/Working-Groups/README.md, community-initiatives-and-working-groups/Working-Groups/metrics-commitee.md, community-initiatives-and-working-groups/Working-Groups/metrics-faq.md, community-initiatives-and-working-groups/Working-Groups/metrics-releases.md, community-initiatives-and-working-groups/Working-Groups/metrics-translation.md, community-initiatives-and-working-groups/Working-Groups/working-groups-repository-structure.md, community-initiatives-and-working-groups/community-initiatives/chaoss-slack-bot.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/README.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/apply-for-a-badge/README.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/apply-for-a-badge/apply-for-in-person-event.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/apply-for-a-badge/apply-for-virtual-event.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/dei-badging-code-of-conduct.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/how-to-contribute.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/reviewing/README.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/reviewing/apply-to-review.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/reviewing/conflict-of-interest-policy.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/reviewing/the-review-process.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/roles-and-responsibility/README.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/roles-and-responsibility/applicant.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/roles-and-responsibility/maintainer.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/roles-and-responsibility/moderator.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/roles-and-responsibility/reviewer.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/event-badging/the-badging-bot.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/project-badging/DEI.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/project-badging/guidelines.md, community-initiatives-and-working-groups/community-initiatives/dei-badging/project-badging/requirements.md, community-initiatives-and-working-groups/community-initiatives/the-mars-project.md
Adding disclaimer to community initiatives and working group folder and its subfolders that this and all subfolders will be deleted in the future as the needed content is moved to chaoss-groups folder and is already live on the website.
Refer PR https://github.com/chaoss/community/pull/538
Signed-off-by: Vinod K. Ahuja <vahuja@unomaha.edu>
=> Adding disclaimer

community-templates/metric-template.md
This removes the Data Use Statement section, as it has been replaced with a common block we add when publishing the metrics page in Wordpress.
=> Remove Data Statement from Metrics Template

chaoss-groups/working-groups.md
This moves the Risk working group to the inactive section.
=> Move Risk WG to inactive

chaoss-groups/local-chapters.md
This PR updates the information about CHAOSS ASIA chapter under the local chapters on the website.
It includes a short intro about the chapter and various ways to get involved in the community.
Closes [#chaoss-asia/issues/3](https://github.com/chaoss/chaoss-asia/issues/3)
=> Update Asia chapter information

.github/ISSUE_TEMPLATE/01-Contribution.yaml, .github/workflows/new-workflow.yml, log-contribution.js
This proposed GitHub action will update the community-contributions.md file in the root of the directory after the creation of an issue using the included template. 
The functionality is tested and working at https://github.com/augurlabs/chaoss-action-bot ... Merging this PR will generate a need to immediately verify and test its functionality here.
=> Proposing a built in action for logging contributions from an issue

chaoss-groups/working-groups.md
Updated to move App Ecosystem to inactive, add the funding WG, and remove some placeholder groups (we can add them back with the appropriate details later).
=> Updated WG list
